CREATE DATABASE COSEGUROS2;
USE COSEGUROS2;
CREATE TABLE `TIPO_DE_AFILIADO` (
  `TIPO_DE_AFILIADO_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(30) NOT NULL
);

CREATE TABLE `PROVINCIA` (
  `PROVINCIA_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(50) NOT NULL
);

CREATE TABLE `LOCALIDADES` (
  `LOCALIDAD_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(50) NOT NULL,
  `PROVINCIA_ID` INT NOT NULL,
  FOREIGN KEY (`PROVINCIA_ID`) REFERENCES `PROVINCIA` (`PROVINCIA_ID`)
);

CREATE TABLE `DELEGACION` (
  `DELEGACION_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(50) NOT NULL,
  `LOCALIDAD_ID` INT NOT NULL,
  FOREIGN KEY (`LOCALIDAD_ID`) REFERENCES `LOCALIDADES` (`LOCALIDAD_ID`)
);

CREATE TABLE `USUARIO` (
  `USUARIO_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(50) NOT NULL,
  `DELEGACION_ID` INT NOT NULL,
  FOREIGN KEY (`DELEGACION_ID`) REFERENCES `DELEGACION` (`DELEGACION_ID`)
);

CREATE TABLE `CIERRE` (
  `CIERRE_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `FECHA_DE_CREACION` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `DELEGACION_ID` INT NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  `TOTAL` INT NOT NULL,
  FOREIGN KEY (`DELEGACION_ID`) REFERENCES `DELEGACION` (`DELEGACION_ID`),
  FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`USUARIO_ID`)
);

CREATE TABLE `METODOS_DE_PAGO` (
  `METODOS_DE_PAGO_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(50) NOT NULL
);

CREATE TABLE `AGRUPADOR` (
  `AGRUPADOR_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(50) NOT NULL
);

CREATE TABLE `NOMENCLADOR` (
  `NOMENCLADOR_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(50) NOT NULL,
  `CODIGO` INT NOT NULL,
  `COSEGURO` DECIMAL NOT NULL,
  `AGRUPADOR_ID` INT,
  FOREIGN KEY (`AGRUPADOR_ID`) REFERENCES `AGRUPADOR` (`AGRUPADOR_ID`)
);
CREATE TABLE `PLANES` (
  `PLANES_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(30) NOT NULL
);

CREATE TABLE `PLANES_PRACTICAS` (
  `NOMENCLADOR_ID` INT NOT NULL,
  `PLANES_ID` INT NOT NULL,
  `PORCENTAJE` INT NOT NULL,
  PRIMARY KEY (`NOMENCLADOR_ID`, `PLANES_ID`),
  FOREIGN KEY (`NOMENCLADOR_ID`) REFERENCES `NOMENCLADOR` (`NOMENCLADOR_ID`),
  FOREIGN KEY (`PLANES_ID`) REFERENCES `PLANES` (`PLANES_ID`)
);

CREATE TABLE `AFILIADOS` (
  `AFILIADOS_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `APELLIDO` VARCHAR(50) NOT NULL,
  `TIPO_DOCUMENTO` VARCHAR(15) UNIQUE NOT NULL,
  `DOCUMENTO` INT UNIQUE NOT NULL,
  `SEXO_BIOLOGICO` VARCHAR(10) NOT NULL,
  `FECHA_DE_NACIMIENTO` VARCHAR(50) NOT NULL,
  `LOCALIDAD_ID` INT NOT NULL,
  `TIPO_DE_AFILIADO_ID` INT NOT NULL,
  FOREIGN KEY (`LOCALIDAD_ID`) REFERENCES `LOCALIDADES` (`LOCALIDAD_ID`),
  FOREIGN KEY (`TIPO_DE_AFILIADO_ID`) REFERENCES `TIPO_DE_AFILIADO` (`TIPO_DE_AFILIADO_ID`),
  CONSTRAINT UQ_DOCUMENTO_TIPO_UNIQUE UNIQUE (DOCUMENTO, TIPO_DOCUMENTO)
);

CREATE TABLE `AFILIADOS_PLANES` (
  `AFILIADO_ID` INT NOT NULL,
  `PLAN_ID` INT NOT NULL,
  `FECHA DE BAJA` DATE,
  `FECHA DE ALTA` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AFILIADO_ID`, `PLAN_ID`),
  FOREIGN KEY (`AFILIADO_ID`) REFERENCES `AFILIADOS` (`AFILIADOS_ID`),
  FOREIGN KEY (`PLAN_ID`) REFERENCES `PLANES` (`PLANES_ID`)
);



CREATE TABLE `BONO` (
  `BONO_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `AFILIADO_ID` INT NOT NULL,
  `FECHA_DE_CREACION` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `METODOS_DE_PAGO_ID` INT NOT NULL,
  `total` INT,
  `CIERRE_ID` INT,
  `USER_ID` INT NOT NULL,
  FOREIGN KEY (`AFILIADO_ID`) REFERENCES `AFILIADOS` (`AFILIADOS_ID`),
  FOREIGN KEY (`METODOS_DE_PAGO_ID`) REFERENCES `METODOS_DE_PAGO` (`METODOS_DE_PAGO_ID`),
  FOREIGN KEY (`CIERRE_ID`) REFERENCES `CIERRE` (`CIERRE_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USUARIO` (`USUARIO_ID`)
);

CREATE TABLE `BONO_ITEM` (
  `BONO_ITEM_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `BONO_ID` INT NOT NULL,
  `NOMENCLADOR_ID` INT NOT NULL,
  `CANTIDAD` INT NOT NULL,
  FOREIGN KEY (`BONO_ID`) REFERENCES `BONO` (`BONO_ID`),
  FOREIGN KEY (`NOMENCLADOR_ID`) REFERENCES `NOMENCLADOR` (`NOMENCLADOR_ID`)
);
